spring:
  cloud:
    config:
      import-check:
        enabled: false
  server:
    port: 9090
  
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true