groups:
  - name: error-alerts
    rules:
      - alert: HighErrorRate
        expr: increase(http_server_requests_seconds_count{status=~"5.."}[30s]) > 10
        for: 0s
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "More than 10 error responses (5xx) in the last 30s"
